apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abhi2330/MY-PORTFOLIO1.git
    targetRevision: main
    path: "/"             
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
